### ISSUE TITLE
Close tag is adding extra characters when using </

### ISSUE THREAD

**Issue by jonathanbarreto** [uzyn/tag#24]
Example when using </

<p></p>p>

**Comment by snowharpy** [comment]
I am sometimes experiencing this as well. For a while everything works, then all of a sudden i start getting double closures like <p>Blah Blah Blah</p>p>

**Comment by wmallafi** [comment]
I am seeing the same issue above. I installed the tag package on the latest ATOM and I see the same issue reported above. Extra characters are being inserted.

**Comment by kngmnaa1e** [comment]
same here

</ul>ul>ul>ul>

**Comment by Bandit** [comment]
Same here.
![2017-04-11_10h31_37](https://cloud.githubusercontent.com/assets/30508/24885476/c4182acc-1ea2-11e7-8c35-fd253f6feeec.png)

**Comment by Bandit** [comment]
Apparently it's to do with the addon being activated more than once - see advice here: https://github.com/mrhanlon/less-than-slash/issues/47

**Comment by MarcoThePoro** [comment]
cooking up a PR real soon

**Comment by uzyn** [comment]
Thanks @MarcoThePoro, looking forward to the PR.

**Comment by MarcoThePoro** [comment]
See https://github.com/uzyn/tag/pull/28 😄

**Comment by uzyn** [comment]
Thank you @MarcoThePoro 

This issue is fixed now, please update Tag package.

**Comment by sjuvonen** [comment]
This issue is still present in 0.5.0, has been around for many moons now, probably always. 

If I open the same file in multiple tabs, every tab instance will trigger an autocomplete when I write in any of the windows as usual. It also seems that after I close one of the tabs, the plugin from that tab will remain active (i.e. not unloaded) and will also perform autocomplete.

I don't know how Atom plugins work but that does sound like potential memory leak.
